import { createApp } from 'vue'
// 'vue-demi'
import App from './App.vue'
import router from './router/index'
// import router from './router'
import { createPinia } from 'pinia'
import { GoogleSpreadsheet } from 'google-spreadsheet';
// import { JWT } from 'google-auth-library';

const state = createPinia()
const app = createApp(App)

// const serviceAccountAuth = new JWT({
//     // env var values here are copied from service account credentials generated by google
//     // see "Authentication" section in docs for more info
//     email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
//     // email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
//     key: process.env.GOOGLE_PRIVATE_KEY,
//     // key: process.env.GOOGLE_PRIVATE_KEY,
//     scopes: [
//       'https://www.googleapis.com/auth/spreadsheets',
//     ],
//   });

app.use(state)
app.use(router)
app.mount('#app')
